### PR TITLE
Add IMS journal metadata

### PR DESCRIPTION
**Pull request by rmzelle**
Closes https://github.com/citation-style-language/journals/pull/42

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, would you mind checking this and https://github.com/citation-style-language/styles/pull/4496 to see if the journal metadata is still up to date? I updated the URLs and added eISSNs, but I didn't check if the journals still use the same reference style.

**Comment by POBrien333** [comment]
@rmzelle 
Checked them all, three recent .pdfs from 2019 per journal. There seems to be a variety of styles used, nothing 100% consistent.

**Comment by rmzelle** [comment]
Great, thanks. Are the instructions more consistent (I had trouble locating reference examples for each journal)?

**Comment by POBrien333** [comment]
Me neither. The documentation URL we used for the parent IMS style in 2017 is down now, so no idea.

**Comment by rmzelle** [comment]
Okay, thanks! Should teach me not to neglect pull requests for 2.5 years :grimacing:

**Pull request merged**
