### PR TITLE
NPG: change parent style for Translational Psychiatry

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/85139/style-request-translational-psychiatry#latest

### CODE REVIEW

**Comment by hagenaue** [comment]
Hi, from the Github comments, it looks like the style for Translational Psychiatry was fixed, but the style listed for Translational Psychiatry in Zotero's style repository is still dated 2014 and doesn't look like the current style:
https://www.zotero.org/styles?q=Translational%20Psychiatry
Any chance that this will be fixed anytime soon?

**Comment by adam3smith** [comment]
We'll fix this (this PR is just the metadata we use to update, not the actual update), but note that you can just use _Nature_ style for the journal (which is what this PR does)

**Comment by MMangnus** [comment]
Hello, it seems to me that this issue is not yet fixed. The _Translational Psychiatry_ style in Zotero was last updated in 2014 and deviates from the actual style used in current articles. Using the _Nature_ style instead of the _Translational Psychiatry_ style does not work since the in-text citations are different (numbers in superscript vs. inside square brackets). Could this perhaps be updated?

**Comment by bwiernik** [comment]
@adam3smith What's the process to run an update of the styles repository against the journals repository?

**Pull request merged**
