### PR TITLE
Institute of Mathematics _template.csl and journals.tab

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/66918/style-for-ima-journals-such-as-teaching-mathematics-and-its-applications
to go with independent parent style: https://github.com/citation-style-language/styles/pull/2876

### CODE REVIEW

**Comment by POBrien333** [comment]
@rmzelle 
This one is ready.

**Comment by rmzelle** [comment]
> This one is ready.

Did we already confirm that all IMA journals use the same citation format?

**Comment by POBrien333** [comment]
I checked them all myself. Apart from the one I deleted from the list again, they all have the same style.

**Comment by rmzelle** [comment]
I had to make some changes, and it was easier to pull your commits into a new PR. Thanks!

**Pull request closed without merging**
