### PR TITLE
Create Future Medicines dependent journals

### PR DESCRIPTION
**Pull request by POBrien333**
to go with new independent parent style future-medicine.csl 
https://github.com/citation-style-language/styles/pull/4834

Future Medicine and Future Medicine Management actually use the same citation style.

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, it's probably better to just update the metadata for future-science-group (see https://github.com/citation-style-language/journals/pull/98 and https://github.com/citation-style-language/styles/pull/4838.

I noticed there are a bunch of Future Medicine journals that you didn't link to the "future-medicine" style. Could you take a look if those should be switched over too? (you can switch the parent in future-science-group/_journals.tab at https://github.com/citation-style-language)/journals/pull/98/files)

**Comment by POBrien333** [comment]
Urgh. Work for nothing then, if we had that already.
I got those journal names from the citation guidelines. So not sure which of the FSG journals follow that same FM style.

**Comment by rmzelle** [comment]
> Urgh. Work for nothing then, if we had that already.
> I got those journal names from the citation guidelines. So not sure which of the FSG journals follow that same FM style.

Would you mind check whether there are clear differences between some of the non-medical FSG journals (like Bioanalysis; https://www.future-science.com/loi/bio) and the FM ones? So that we at least know we need two separate FSG and FM CSL independent styles?

If that's the case, we can at least merge https://github.com/citation-style-language/journals/pull/98/ and https://github.com/citation-style-language/styles/pull/4838, even if some medical journals are still misassigned to FSG instead of FM (at least it should be an improvement).

**Comment by POBrien333** [comment]
Just checked. There is minimal differences, so I would say let's keep the two styles. Potentially we could just merge it all into one section/files.

**Comment by rmzelle** [comment]
> There is minimal differences, so I would say let's keep the two styles. I guess it would make sense then to just put it all together into the FSG files?

Put it all together in the "journals" repo? That's what I did in https://github.com/citation-style-language/journals/pull/98, where I updated the existing metadata for "future-science-group" (based on your original PR). Sounds like I can merge that, then.

**Comment by POBrien333** [comment]
One step ahead. Great :)

**Comment by rmzelle** [comment]
Done. Thanks!

**Pull request closed without merging**
