### PR TITLE
Add some badges in README

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by rmzelle** [comment]
@zuphilip, thanks. Can you give some links here on documentation of these badges? (i.e., how you came up with these links)

**Comment by zuphilip** [comment]
Travis badge: https://docs.travis-ci.com/user/status-images/ 
Shields badges: http://shields.io/

**Comment by rmzelle** [comment]
Thanks! (GitHub nowadays already shows the license in the toolbar, but I guess it can't hurt to have a badge as well; https://github.com/blog/2252-license-now-displayed-on-repository-overview)

**Comment by rmzelle** [comment]
(and I'd be happy to accept them for the other repos)

**Pull request merged**
