### PR TITLE
Update _journals.tab (Springer BMC journals)

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/72036/csl-vancouver-bmc-bioinformatics-doi
(Let me know if you want this solved in a different way).

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks, @POBrien333 !
This PR will change the CSL file that's downloaded by https://www.zotero.org/styles/bmc-bioinformatics, correct?

**Comment by POBrien333** [comment]
Yes

**Comment by rmzelle** [comment]
Oh, hey Shaun. Nice seeing you at PoreCamp Vancouver. Small world :).

Actually, @POBrien333, for the big publishers we avoid editing _journals.tab and make any corrections in the supplementary files like _extra.tab. That way, when we get a new batch of journal metadata we can just replace _journals.tab without having to worry about any manual corrections we made in the past.

**Comment by rmzelle** [comment]
(and @POBrien333, if you want to be thorough, you could check a handful of the other BMC journals and check if they also use the BMC style)

**Comment by POBrien333** [comment]
Do the settings in the extra.tab override anything in the journals.tab?
Will change this PR accordingly and check the other journals, too.

**Comment by POBrien333** [comment]
I've checked 50% of the journals. Fairly easy as one just needs to adapt the url to the submission-guidelines with the journal title.
All use the biomed-central style that displays doi:xxx if available.

**Comment by rmzelle** [comment]
> All use the biomed-central style that displays doi:xxx if available.

Okay, we can just switch all of them over, then. The Springer metadata we get always seems a bit sloppy when it comes to specifying the citation formats of the BMC journals.

> Do the settings in the extra.tab override anything in the journals.tab?

The whole entry gets replaced (with matching on the generated style ID), if I remember correctly.

**Comment by sjackman** [comment]
Hi, Rintze. Small world indeed! Thanks for your efforts with CSL. It makes my life so much easier! I write my papers in Markdown and use Pandoc to convert them to DOCX for my collaborators and TEX/PDF for submission to a journal.

**Comment by rmzelle** [comment]
@POBrien333, is it just an oversight that you didn't include the following BMC journals in the _extra.tab file?:

bmc-sports-science-medicine-and-rehabilitation
bmc-research-notes
bmc-psychology
bmc-pharmacology-and-toxicology
bmc-obesity
bmc-nutrition
bmc-biophysics

**Comment by POBrien333** [comment]
that was an oversight. I just copied all the ones from the journals.tab file.

**Comment by rmzelle** [comment]
> I just copied all the ones from the journals.tab file.

The others should be all in there, but it looks like they're scattered around a bit. I just noticed the discrepancy between how many BMC styles the script generated and the number of styles you added in _extra.tab.

**Comment by POBrien333** [comment]
Yeah. Found them now and added them all. :)

**Comment by rmzelle** [comment]
Thanks! (just had to fix some column delimiters in _extra.tab)

**Comment by sjackman** [comment]
Thanks for these fixes! CSL and Pandoc makes my life so much better. 😀

**Comment by rmzelle** [comment]
You're welcome :)

**Pull request merged**
