### PR TITLE
Add "Reviews of Environmental Contamination and Toxicology" to Springer's _extra.tab

### PR DESCRIPTION
**Pull request by damnation333**
Just follows the basic Sprinter author-date style.
Per request here: https://github.com/citation-style-language/styles/issues/2238

### CODE REVIEW

**Comment by zuphilip** [comment]
FYI I can also ask Springer for the current list of all their journals to update that more. However, I cannot work on that further then at the moment. Let me know if you want the list to work with that.

**Comment by rmzelle** [comment]
> FYI I can also ask Springer for the current list of all their journals to update that more. However, I cannot work on that further then at the moment. Let me know if you want the list to work with that.

Sure. (@damnation333 is just closing open issues here, which is great, but we can update the entire set of journal as well; it's probably easier for us to do more frequent updates of the "journals" metadata anyway)

**Comment by rmzelle** [comment]
(also, @damnation333, in the future, could you give the PRs to the "journals" repo a more meaningful title? The automatic titles in the "styles" repo normally already mention the style file you're updating, so that's quite clear, but here we have many "_journals.tab" and "_extra.tab" files, so the automatic suggested PR titles are a bit useless)

**Comment by damnation333** [comment]
sure. Will do that @rmzelle . :)
@zuphilip , happy to work with an updated Springer list, if you provide it.

**Pull request merged**
