### PR TITLE
Create AOSIS dependent styles

### PR DESCRIPTION
**Pull request by POBrien333**
closes https://github.com/citation-style-language/journals/issues/33

Attached the .xlsx in case you need to change anything: [aosis-journals.xlsx](https://github.com/citation-style-language/journals/files/6154779/aosis-journals.xlsx)

### CODE REVIEW

**Comment by POBrien333** [comment]
Should have everything now, @rmzelle .

Hope I did it all correctly! :)

**Comment by POBrien333** [comment]
Onderstepoort Journal of Veterinary Research exists on repository already.

**Comment by rmzelle** [comment]
> Hope I did it all correctly! :)

A few small errors in the template, but otherwise it all looked good. Thanks!

**Comment by rmzelle** [comment]
@POBrien333, thanks!

**Comment by POBrien333** [comment]
Awesome. Thank you.
Am I seeing this correctly that you set all styles as author-date, although some are numeric?

**Comment by rmzelle** [comment]
Oops, I thought our tests would have caught that. Could you file a new PR to add a FORMAT field to the AOSIS journal metadata?

**Comment by rmzelle** [comment]
And we had already rolled over to 10000+ styles a few days ago (https://twitter.com/librarianjason/status/1371547108889792518?s=21). Thanks for your help getting CSL there!

**Comment by rmzelle** [comment]
> Oops, I thought our tests would have caught that.

Actually, turns out that the Vancouver parent was labelled as "author-date" instead of "numeric". Should be all good now.

**Comment by POBrien333** [comment]
Ahhh. Thanks for fixing that.

**Pull request merged**
