### PR TITLE
Update _journals.tab for NRC journals

### PR DESCRIPTION
**Pull request by damnation333**
Add 3 journals following one of the two independent parents as requested here https://github.com/citation-style-language/journals/issues/10
applied-physiology-nutrition-and-metabolism has existed as its own dependent style and should be deleted.
(it's not alphabetic. Happy to sort it out if want)

### CODE REVIEW

**Comment by rmzelle** [comment]
See also https://github.com/citation-style-language/styles/commit/2c2398fed4f3011fce1f927936d6f52518e1ae56

**Comment by rmzelle** [comment]
@damnation333, you again had some issues with spaces instead of tabs between fields. Personally, I almost always edit these tab-delimited files by copy and pasting their contents into a Google Docs spreadsheet, making my edits, and copy and pasting the result back.

Otherwise, thanks!

**Comment by rmzelle** [comment]
> (it's not alphabetic. Happy to sort it out if want)

I already quickly sorted it in Google Docs.

**Comment by rmzelle** [comment]
(This should mostly wrap up #10)

**Comment by rmzelle** [comment]
#10

**Comment by damnation333** [comment]
@rmzelle 
Thanks. I edited the files just in Firefox. I will stop doing that then and do it in NP++ from now on.
Sorry.

**Comment by rmzelle** [comment]
Yes, definitely use either a good text editor or spreadsheet program (the latter are usually much easier because they automatically put everything in columns, making the files much easier to read)

**Pull request merged**
