### PR TITLE
Add International Journal of Hyperthermia to T&F _extra.tab

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/comment/299865/#Comment_299865

### CODE REVIEW

**Comment by POBrien333** [comment]
@rmzelle 
Seeing that I made two more PRs for T&F, would it make sense to combine those into one PR, so we can get these closed?
#62, #64, #77

**Comment by rmzelle** [comment]
No need. I mostly just need to find some time to address these (journals PRs always take more time since I always run the script locally and need to generate the accompanying styles repo PR).

**Comment by rmzelle** [comment]
Looks like the journal doesn't specify a specific journal style (anymore?), but let's just merge this. Can't hurt to have a dependent style for the journal.

**Comment by rmzelle** [comment]
Overdue thanks!

**Comment by POBrien333** [comment]
> 
> 
> No need. I mostly just need to find some time to address these (journals PRs always take more time since I always run the script locally and need to generate the accompanying styles repo PR).

Ah, I see. 
Thanks for getting those styles up. :)

**Pull request merged**
