### PR TITLE
Update _extra.tab

### PR DESCRIPTION
**Pull request by damnation333**
To superseed https://github.com/citation-style-language/styles/pull/2022/files

### CODE REVIEW

**Comment by damnation333** [comment]
just double checked and it is in the _journals.tab. Don't know why I didn't find it the first time. Weird. Sorry for the false alarm.

**Comment by rmzelle** [comment]
> just double checked and it is in the _journals.tab. Don't know why I didn't find it the first time. Weird.

Yeah, you couldn't really have known, but the journal metadata in this repo for T&F hasn't been synchronized the repository in quite a while. See the comment thread at https://github.com/citation-style-language/utilities/commit/2b53ca8deba7e63373aec3bca5265619daae280f. We were hoping to get fresh metadata from T&F before attempting this, but it's often not easy to get a hold of the right person.

For now I just generated this particular style from the metadata and added it by hand: https://github.com/citation-style-language/styles/commit/22a8adc436472ed8df255e6723764f31dc38f3a3

**Comment by rmzelle** [comment]
(it would also be good if we kept better track of when metadata was last comprehensively updated for each publisher, and make sure we're alerted when the "journals" repo is out of sync with the "styles" repo)

**Comment by rmzelle** [comment]
(I created a ticket for this at https://github.com/citation-style-language/journals/issues/30)

**Pull request closed without merging**
