### PR TITLE
add Current Medical Research and Opinion

### PR DESCRIPTION
**Pull request by damnation333**
https://forums.zotero.org/discussion/comment/246647#Comment_246647
Not 100% sure about this as there is no other style in here that uses the T&F NLM style with numeric format.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks. I just moved the line over to the `_extra.tab` file. As explained at https://github.com/citation-style-language/journals#_extratab, for large publishers we've found it easier to use `_journals.tab` solely for the list of journals as generated from the journal metadata we get from the publisher. Any corrections can then take place in `_extra.tab` (to add additional journals), `_rename.tab` (to rename them), and `_skip.txt` (to skip journals). That way we can periodically update `_journals.tab` with new publisher-provided metadata, without having to make all the corrections/additions again in that file.

> Not 100% sure about this as there is no other style in here that uses the T&F NLM style with numeric format.

What do you mean, exactly? There seem to be 50 styles in `_journals.tab` already that use taylor-and-francis-national-library-of-medicine.

**Comment by rmzelle** [comment]
Also, do you want to give the `generate_styles.rb` Ruby script a try, or would you rather we run it for you to create the dependent style?

**Comment by damnation333** [comment]
> What do you mean, exactly? There seem to be 50 styles in _journals.tab already that use taylor-and-francis-national-library-of-medicine.
Ignore that. Sometimes the search function in Firefox doesn't like me.

> Also, do you want to give the generate_styles.rb Ruby script a try, or would you rather we run it for you to create the dependent style?
I wouldn't know where to start with this and I am very new to this all.

**Comment by rmzelle** [comment]
@damnation333, thanks. (I had to add tabs to delimit the fields)

**Pull request merged**
