### PR TITLE
Create Mary Ann Liebert dependent styles

### PR DESCRIPTION
**Pull request by POBrien333**
in addition to https://github.com/citation-style-language/styles/pull/5957

This is in communication with the publisher and a list was provided to me.

### CODE REVIEW

**Comment by POBrien333** [comment]
Hi @adam3smith 
I'm aware you're very busy these days.
Would you be able to look at this PR though in the coming days as I'd like to close this project with Heather. Thank you :)

**Comment by bwiernik** [comment]
Lgtm. Thanks!

**Comment by POBrien333** [comment]
Ahh, you're a star. Thanks, Brenton! :)

**Comment by POBrien333** [comment]
It looks like the styles are not appearing on the repository. Who do we need to ask to get that looked into?

**Comment by bwiernik** [comment]
@retorquere Anything amiss with the actions?

**Comment by POBrien333** [comment]
Hi @retorquere 
Sorry for following up on this so soon again, but were you able to look into this issue? Thank you.

**Comment by retorquere** [comment]
The journals repo don't have any kind of merge logic, only the styles and locales repos do. Should the journals repo behave like locales?

This might require changes to Sheldon. At some point we're going to have to overhaul Sheldon. There's a lot of cruft, and I'm just not really current on ruby.

**Comment by adam3smith** [comment]
I don't think we want to automate this: good to have a human eye on this before merging -- someone actually has to run the sync script locally and the push the changes. I'm afraid that won't be me until later this week

**Comment by retorquere** [comment]
So nothing to do for me here?

**Comment by POBrien333** [comment]
Ahh. Great. Thanks for looking into this.
I'll wait till you let me know when you've ran the script then. thx

**Pull request merged**
