### PR TITLE
Add Journal of Micropaleontology to Copernicus

### PR DESCRIPTION
**Pull request by POBrien333**
via https://github.com/citation-style-language/styles/pull/3085#issuecomment-342738522

### CODE REVIEW

**Comment by rmzelle** [comment]
Oh, I forgot that we already have Copernicus in the "journals" repo. Makes life much easier if it uses the standard Copernicus style :).

**Comment by POBrien333** [comment]
luckily the example search found it :)

**Comment by rmzelle** [comment]
Thanks!

**Comment by rmzelle** [comment]
(I forgot to remove the journal from the other data set. Now fixed)

**Pull request merged**
