### PR TITLE
Update Frontiers _template.csl

### PR DESCRIPTION
**Pull request by damnation333**

### CODE REVIEW

**Comment by rmzelle** [comment]
(merged by hand into #27)

**Comment by damnation333** [comment]
Does that mean you can change two or more files in one PR? If so how?

**Comment by rmzelle** [comment]
> Does that mean you can change two or more files in one PR? If so how?

Yes, most certainly!

If you look at this pull request, it says at the top: "damnation333 wants to merge 1 commit into citation-style-language:master from damnation333:patch-11". So when you created this pull request, GitHub created a new branch ("patch-11") in your fork of our repository. Any changes you make in that branch (at https://github.com/damnation333/journals/tree/patch-11), will automatically show up in this pull request. You can also check out the "patch-11" branch of your fork on your computer with a Git client, make additional changes, commit those changes, and then push them to the online copy.

**Comment by rmzelle** [comment]
And the GitHub website is primarily designed to make it easy to make simple changes. For anything fancy (like changing hundreds or thousands of files at a time in a single PR), you would always use a locale Git client.

**Pull request closed without merging**
